name: List Tags

on:
  push:
    branches:
      - main

jobs:
  list-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Tags
        id: tags
        run: |
          echo "TAGS=$(git tag --sort=-creatordate)" >> $GITHUB_ENV
          echo "Tag list:"
          echo "${TAGS}"

      - name: Select Tag
        id: select-tag
        run: |
          echo "Available tags:"
          IFS=$'\n' read -rd '' -a tag_array <<< "${TAGS}"
          for tag in "${tag_array[@]}"; do
            echo "- $tag"
          done

        env:
          TAGS: ${{ env.TAGS }}
