name: List Tags

on:
  push:
    branches:
      - main

jobs:
  list-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Tags
        id: tags
        run: echo "TAGS=$(git tag --sort=-creatordate)" >> $GITHUB_ENV

      - name: Select Tag
        id: select-tag
        run: |
          echo "Available tags:"
          for tag in ${{ env.TAGS }}; do
            echo "- $tag"
          done

        env:
          SELECTED_TAG: ${{ env.TAGS }}
